AdColonyRewardListener listener = new AdColonyRewardListener() {
    @Override
    public void onReward(AdColonyReward reward) {
        /** Query the reward object for information here */
    }
};

/** Set reward listener for your app to be alerted of reward events */
AdColony.setRewardListener(listener);
